server:
  port: 8082

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_blog
    username: root
    password: 12345678
    # redis
  redis:
    database: 0 # 选择库
    host: localhost
    port: 6379
    client-type: lettuce # 使用lettuce客户端连接
    #    lettuce连接配置
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1000ms
        min-idle: 0


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tb_
  type-aliases-package: "com.red.entity"


user:
  user-id: 8888888888888888888




